=== OSenden/Apprendre-XML/00_XML_DTD/public_html/boite.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
boite
- contient de 0 à N couleurs
- possède éventuellement une capacité
- a une dimension composée d'une largeur, d'une hauteur et d'une longueur

Une couleur possède un attribut typeDeCouleur qui peut être rouge 
ou vert ou bleu ou blanc.
Par défaut la couleur est "blanc"
-->
<!ELEMENT boite (couleur*,capacite?,dimensions)>
<!ELEMENT dimensions (largeur,hauteur,longueur)>
<!ELEMENT capacite (#PCDATA)>
<!ELEMENT largeur (#PCDATA)>
<!ELEMENT hauteur (#PCDATA)>
<!ELEMENT longueur (#PCDATA)>
<!ELEMENT couleur EMPTY>
<!ATTLIST couleur typeDeCouleur (rouge|vert|bleu|blanc) "blanc">

=== OSenden/Apprendre-XML/00_XML_DTD/public_html/boite.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE boite SYSTEM "boite.dtd" >
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<boite>
    <couleur typeDeCouleur="rouge" />       
    <couleur typeDeCouleur="bleu" />
    <capacite>2000</capacite>
    <dimensions>
        
        <largeur>10</largeur>
        <hauteur>20</hauteur>
        <longueur>10</longueur>
    </dimensions>
    
</boite>
